#!/bin/bash
# author: Robin Wen
# date: 2014-11-20 11:54:48
# desc: Auto install and config apt-fast, use apt-fast instead apt-get. See at: http://xmodulo.com/speed-slow-apt-get-install-debian-ubuntu.html 
# attention: Use this script in debian 7.6 and run as root.

# Config locale
echo "" > /etc/default/locale
echo "#  File generated by update-locale" >> /etc/default/locale
echo "LC_CTYPE=en_US.UTF-8" >> /etc/default/locale
echo "LC_ALL=" >> /etc/default/locale
echo "LANG=en_US.UTF-8" >> /etc/default/locale
echo "export LC_ALL=C" >> /root/.bashrc
source /root/.bashrc
locale-gen
echo "Config locale finished!"

# Install and config apt-fast
apt-get -y install unzip
apt-get -y install aria2
wget https://github.com/ilikenwf/apt-fast/archive/master.zip
unzip master.zip
cp ./apt-fast-master/apt-fast /usr/bin
cp ./apt-fast-master/apt-fast.conf /etc
cp ./apt-fast-master/man/apt-fast.8 /usr/share/man/man8
gzip /usr/share/man/man8/apt-fast.8
cp ./apt-fast-master/man/apt-fast.conf.5 /usr/share/man/man5
gzip /usr/share/man/man5/apt-fast.conf.5

# Config apt-fast source
sed '/#MIRRORS/a\MIRRORS=('http://mirrors.163.com/debian,http://mirrors.sohu.com/debian,http://ftp.cn.debian.org/debian')' /etc/apt-fast.conf -i

# Update apt-fast
apt-fast update
echo "apt-fast update finished!"

# remove download media and unzip dir
rm -rf master.zip 
rm -rf apt-fast-master

echo "Auto install and config apt-fast finished!"
